github_calendar_colors = {
    'React': {'tech_type': 'Frontend', 'tech_color':'#80DEEA', 'logo_path': '/static/img/react.png'},
    'Angular': {'tech_type': 'Frontend', 'tech_color':'#B71C1C', 'logo_path': '/static/img/angular.png'},
    'Svelte': {'tech_type': 'Frontend', 'tech_color':'#d6e5e5', 'logo_path': '/static/img/svelte.png'},
    'Vue': {'tech_type': 'Frontend', 'tech_color':'#35495e', 'logo_path': '/static/img/vue.png'},

    'Django': {'tech_type': 'Backend', 'tech_color':'#004D40', 'logo_path': '/static/img/django.png'},
    'Spring': {'tech_type': 'Backend', 'tech_color':'#8BC34A', 'logo_path': '/static/img/spring.png'},
    'Nodejs': {'tech_type':'Backend', 'tech_color':'#4CAF50', 'logo_path': '/static/img/nodejs.png'},
    'Laravel': {'tech_type': 'Backend', 'tech_color':'#E64E40', 'logo_path': '/static/img/laravel.png'},
    'Flask': {'tech_type': 'Backend', 'tech_color':'#000000', 'logo_path': '/static/img/flask.png'},

    'Android': {'tech_type': 'Mobile', 'tech_color':'#96C362', 'logo_path': '/static/img/android.png'},
    'Flutter': {'tech_type': 'Mobile', 'tech_color':'#40c4ff', 'logo_path': '/static/img/flutter.png'},
    'iOS': {'tech_type': 'Mobile', 'tech_color':'#FF6D00', 'logo_path': '/static/img/ios.png'},
    'React Native': {'tech_type': 'Mobile', 'tech_color':'#80deea', 'logo_path': '/static/img/react native.png'},

    'Mysql': {'tech_type': 'Database', 'tech_color':'#EB7D15', 'logo_path': '/static/img/mysql.png'},
    'Mariadb': {'tech_type': 'Database', 'tech_color':'#006064', 'logo_path': '/static/img/mariadb.png'},
    'Postgresql': {'tech_type': 'Database', 'tech_color':'#0277BD', 'logo_path': '/static/img/postgresql.png'},
    'Sqlite': {'tech_type': 'Database', 'tech_color':'#3598d7', 'logo_path': '/static/img/sqlite.png'},
    'Mongodb': {'tech_type': 'Database', 'tech_color':'#4caf50', 'logo_path': '/static/img/mongodb.png'},
    'Redis': {'tech_type': 'Database', 'tech_color':'#bd201f', 'logo_path': '/static/img/redis.png'},

    'Docker': {'tech_type': 'Devops', 'tech_color':'#03a9f4', 'logo_path': '/static/img/docker.png'},
    'Kubernetes': {'tech_type': 'Devops', 'tech_color':'#0277bd', 'logo_path': '/static/img/kubernetes.png'},

    'HTML': {'tech_type': 'Language', 'tech_color':'#E65100', 'logo_path': '/static/img/html.png'},
    'JavaScript': {'tech_type': 'Language', 'tech_color':'#FFD600', 'logo_path': '/static/img/javascript.png'},
    'Python': {'tech_type': 'Language', 'tech_color':'#0277BD', 'logo_path': '/static/img/python.png'},
    'Swift': {'tech_type': 'Language', 'tech_color':'#E64A19', 'logo_path': '/static/img/swift.png'},
    'CSS': {'tech_type': 'Language', 'tech_color':'#0277BD', 'logo_path': '/static/img/css.png'},
    'Go': {'tech_type': 'Language', 'tech_color':'#4DD0E1', 'logo_path': '/static/img/go.png'},
    'C': {'tech_type': 'Language', 'tech_color':'#3b5aab', 'logo_path': '/static/img/c.png'},
    'C#': {'tech_type': 'Language', 'tech_color':'#2f027bad', 'logo_path': '/static/img/c_sharp.png'},
    'Ruby': {'tech_type': 'Language', 'tech_color':'#b00640', 'logo_path': '/static/img/ruby.png'},
    'C++': {'tech_type': 'Language', 'tech_color':'#0086D4', 'logo_path': '/static/img/c++.png'},
    'Java': {'tech_type': 'Language', 'tech_color':'#F44336', 'logo_path': '/static/img/java.png'},
    'Dart': {'tech_type': 'Language', 'tech_color':'#42A5F5', 'logo_path': '/static/img/dart.png'},
    'Smali': {'tech_type': 'Language', 'tech_color':'#1F52ED', 'logo_path': '/static/img/smali.png'},
    'Kotlin': {'tech_type': 'Language', 'tech_color':'#806EE3', 'logo_path': '/static/img/kotlin.png'},
    'Rust': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/rust.png'},
    'TypeScript': {'tech_type': 'Language', 'tech_color':'#1976D2', 'logo_path': '/static/img/typescript.png'},
    'PHP': {'tech_type': 'Language', 'tech_color':'#BFADF3', 'logo_path': '/static/img/php.png'},
    'Nix': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/nix.png'},
    'FreeMarker': {'tech_type': 'Language', 'tech_color':'#181816', 'logo_path': '/static/img/freemarker.png'},
    'Batchfile': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/batchfile.png'},
    'Shell': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/shell.png'},
    'Nimrod': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/nimrod.png'},
    'LLVM': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/llvm.png'},
    'SCSS': {'tech_type': 'Language', 'tech_color':'#E55F92', 'logo_path': '/static/img/scss.png'},
    'ASP': {'tech_type': 'Language', 'tech_color':'#0088c8', 'logo_path': '/static/img/asp.png'},
    'Gentoo Ebuild': {'tech_type': 'Language', 'tech_color':'#cecee8', 'logo_path': '/static/img/gentoo ebuild.png'},
    'Cuda': {'tech_type': 'Language', 'tech_color':'#80bc00', 'logo_path': '/static/img/cuda.png'},
    'VimL': {'tech_type': 'Language', 'tech_color':'#51923E', 'logo_path': '/static/img/viml.png'},
    'Erlang': {'tech_type': 'Language', 'tech_color':'#a90533', 'logo_path': '/static/img/erlang.png'},
    'Json': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/json.png'},
    'Ruby on Rails': {'tech_type': 'Language', 'tech_color':'#CF4312', 'logo_path': '/static/img/ruby on rails.png'},
    'fish': {'tech_type': 'Language', 'tech_color':'#599D47', 'logo_path': '/static/img/fish.png'},
    'Less': {'tech_type': 'Language', 'tech_color':'#274977', 'logo_path': '/static/img/less.png'},
    'Jupyter Notebook': {'tech_type': 'Language', 'tech_color':'#EF960F', 'logo_path': '/static/img/jupyter notebook.png'},
    'ChucK': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/chuck.png'},
    'KiCad': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/kicad.png'},
    'Verilog': {'tech_type': 'Language', 'tech_color':'#1a348f', 'logo_path': '/static/img/verilog.png'},
    'Elixir': {'tech_type': 'Language', 'tech_color':'#6d547f', 'logo_path': '/static/img/elixir.png'},
    'Scala': {'tech_type': 'Language', 'tech_color':'#f283a5', 'logo_path': '/static/img/scala.png'},
    'Prolog': {'tech_type': 'Language', 'tech_color':'#c4643a', 'logo_path': '/static/img/prolog.png'},
    'AsciiDoc': {'tech_type': 'Language', 'tech_color':'#1f8197', 'logo_path': '/static/img/asciidoc.png'},
    'OCaml': {'tech_type': 'Language', 'tech_color':'#f5ac63', 'logo_path': '/static/img/ocaml.png'},
    'CMake': {'tech_type': 'Language', 'tech_color':'#064f8c', 'logo_path': '/static/img/cmake.png'},
    'Smalltalk': {'tech_type': 'Language', 'tech_color':'#f7c400', 'logo_path': '/static/img/smalltalk.png'},
    'SystemVerilog': {'tech_type': 'Language', 'tech_color':'#2c087e', 'logo_path': '/static/img/systemverilog.png'},
    'Clojure': {'tech_type': 'Language', 'tech_color':'#8DD646', 'logo_path': '/static/img/clojure.png'},
    'Cucumber': {'tech_type': 'Language', 'tech_color':'#00a818', 'logo_path': '/static/img/cucumber.png'},
    'Lua': {'tech_type': 'Language', 'tech_color':'#7e42ff', 'logo_path': '/static/img/lua.png'},
    'ActionScript': {'tech_type': 'Language', 'tech_color':'#f0f0f0', 'logo_path': '/static/img/actionscript.png'},
    'Haskell': {'tech_type': 'Language', 'tech_color':'#5e5086', 'logo_path': '/static/img/haskell.png'},
    'Slim': {'tech_type': 'Language', 'tech_color':'#9BBB7A', 'logo_path': '/static/img/slim.png'},
    'SQLPL': {'tech_type': 'Language', 'tech_color':'#E6586C', 'logo_path': '/static/img/sqlpl.png'},
    'Makefile': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/makefile.png'},
    'Groovy': {'tech_type': 'Language', 'tech_color':'#619CBC', 'logo_path': '/static/img/groovy.png'},
    'JSX': {'tech_type': 'Language', 'tech_color':'#8650A1', 'logo_path': '/static/img/jsx.png'},
    'OpenCL': {'tech_type': 'Language', 'tech_color':'#E64D29', 'logo_path': '/static/img/opencl.png'},
    'GLSL': {'tech_type': 'Language', 'tech_color':'#4386b5', 'logo_path': '/static/img/glsl.png'},
    'Perl6': {'tech_type': 'Language', 'tech_color':'#ffff00', 'logo_path': '/static/img/perl6.png'},
    'Cython': {'tech_type': 'Language', 'tech_color':'#f2d413', 'logo_path': '/static/img/cython.png'},
    'Scheme': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/scheme.png'},
    'Assembly': {'tech_type': 'Language', 'tech_color':'#5C6BC0', 'logo_path': '/static/img/assembly.png'},
    'Emacs Lisp': {'tech_type': 'Language', 'tech_color':'#9575CD', 'logo_path': '/static/img/emacs lisp.png'},
    'PowerShell': {'tech_type': 'Language', 'tech_color':'#6aaed7', 'logo_path': '/static/img/powershell.png'},
    'Smarty': {'tech_type': 'Language', 'tech_color':'#F5C845', 'logo_path': '/static/img/smarty.png'},
    'Vala': {'tech_type': 'Language', 'tech_color':'#403757', 'logo_path': '/static/img/vala.png'},
    'Isabelle': {'tech_type': 'Language', 'tech_color':'#000000', 'logo_path': '/static/img/isabelle.png'},
    'M4Sugar': {'tech_type': 'Language', 'tech_color':'#e0e2e3', 'logo_path': '/static/img/m4sugar.png'},
}
